import { StyleSheet } from "react-native"; 
import globalStyles from '../../styles';

export const styles = StyleSheet.create({
  ...globalStyles.layout,
  ...globalStyles.typography,
  ...globalStyles.components,
  screen: {
    flex: 1,
    backgroundColor: "#F4F5F7",
  },
  scroll: {
    flex: 1,
  },
  content: {
    paddingBottom: 40,
  },

  // Personal Header
  personalHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 20,
    paddingTop: 10,
    paddingBottom: 24,
  },
  greetingRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 16,
  },
  headerAvatarLarge: {
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: "#A93C40",
    alignItems: "center",
    justifyContent: "center",
    shadowColor: "#A93C40",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
  },
  headerAvatarLargeText: {
    fontSize: 22,
    fontWeight: "800",
    color: "#FFFFFF",
  },
  greetingTime: {
    fontSize: 15,
    color: "#6B7280",
    fontWeight: "500",
  },
  greetingName: {
    fontSize: 24,
    fontWeight: "800",
    color: "#1A2B4A",
    letterSpacing: -0.5,
  },
  headerActions: {
    flexDirection: "row",
    gap: 12,
  },
  iconBtn: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: "#FFFFFF",
    alignItems: "center",
    justifyContent: "center",
    shadowColor: "#1A2B4A",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 8,
    elevation: 2,
  },
  badge: {
    position: "absolute",
    top: 6,
    right: 8,
    backgroundColor: "#A93C40",
    borderRadius: 10,
    minWidth: 18,
    height: 18,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 4,
    borderWidth: 1.5,
    borderColor: "#FFFFFF",
  },
  badgeText: {
    color: "#FFFFFF",
    fontSize: 10,
    fontWeight: "800",
  },

  // Personal Section
  personalSection: {
    paddingHorizontal: 20,
    marginBottom: 32,
  },
  cardsStack: {
    gap: 12,
  },
  cardSectionTitle: {
    fontSize: 14,
    fontWeight: "700",
    color: "#6B7280",
    textTransform: "uppercase",
    letterSpacing: 0.5,
    marginBottom: 12,
  },

  // Fresher Cards
  dayCounter: {
    fontSize: 14,
    fontWeight: "600",
    color: "#A93C40",
    marginBottom: 4,
  },
  fresherPeopleCard: {
    backgroundColor: "#FFFFFF",
    borderRadius: 24,
    padding: 20,
    shadowColor: "#1A2B4A",
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.04,
    shadowRadius: 24,
    elevation: 3,
  },
  peopleRow: {
    flexDirection: "row",
    gap: 16,
  },
  personItem: {
    flex: 1,
    alignItems: "center",
    backgroundColor: "#F8F9FA",
    padding: 16,
    borderRadius: 16,
  },
  personImage: {
    width: 56,
    height: 56,
    borderRadius: 28,
    marginBottom: 12,
  },
  personImagePlaceholder: {
    backgroundColor: "#C7D2FE",
    alignItems: "center",
    justifyContent: "center",
  },
  personImagePlaceholderText: {
    fontSize: 20,
    fontWeight: "700",
    color: "#4338CA",
  },
  personName: {
    fontSize: 15,
    fontWeight: "700",
    color: "#1A2B4A",
  },
  personRole: {
    fontSize: 13,
    color: "#6B7280",
    marginTop: 2,
  },

  upNextCard: {
    backgroundColor: "#1A2B4A",
    borderRadius: 20,
    padding: 20,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  upNextLeft: {
    flex: 1,
  },
  upNextLabel: {
    color: "#9BA3AE",
    fontSize: 13,
    fontWeight: "600",
    textTransform: "uppercase",
    letterSpacing: 0.5,
    marginBottom: 4,
  },
  upNextTitle: {
    color: "#FFFFFF",
    fontSize: 18,
    fontWeight: "700",
    marginBottom: 4,
  },
  upNextTime: {
    color: "#D1D5DB",
    fontSize: 14,
  },
  progressRing: {
    width: 48,
    height: 48,
    borderRadius: 24,
    borderWidth: 3,
    borderColor: "#4B5563",
    borderTopColor: "#FFFFFF",
    alignItems: "center",
    justifyContent: "center",
  },
  progressText: {
    color: "#FFFFFF",
    fontSize: 13,
    fontWeight: "700",
  },

  clubNudgeCard: {
    backgroundColor: "#FFFFFF",
    borderRadius: 20,
    padding: 20,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  clubNudgeInfo: {
    flex: 1,
  },
  clubNudgeTitle: {
    fontSize: 16,
    fontWeight: "700",
    color: "#1A2B4A",
  },
  clubNudgeDesc: {
    fontSize: 14,
    color: "#6B7280",
    marginTop: 4,
  },

  // Continuing Student Cards
  joinedClubCard: {
    backgroundColor: "#FFFFFF",
    borderRadius: 20,
    padding: 20,
    marginBottom: 12,
  },
  clubRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 16,
  },
  clubAvatarMock: {
    width: 48,
    height: 48,
    borderRadius: 16,
    backgroundColor: "#FEF3C7",
    alignItems: "center",
    justifyContent: "center",
  },
  clubAvatarImage: {
    width: 48,
    height: 48,
    borderRadius: 16,
  },
  clubAvatarText: {
    fontSize: 18,
    fontWeight: "800",
    color: "#D97706",
  },
  clubInfo: {
    flex: 1,
  },
  clubName: {
    fontSize: 16,
    fontWeight: "700",
    color: "#1A2B4A",
  },
  clubUpdate: {
    fontSize: 14,
    color: "#6B7280",
    marginTop: 4,
  },

  // Elevated Role Cards
  elevatedCard: {
    backgroundColor: "#FFFFFF",
    borderRadius: 20,
    padding: 20,
    marginBottom: 12,
    borderLeftWidth: 4,
    borderLeftColor: "#4338CA",
    shadowColor: "#1A2B4A",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.03,
    shadowRadius: 12,
  },
  elevatedHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 8,
  },
  elevatedTitle: {
    fontSize: 16,
    fontWeight: "700",
    color: "#1A2B4A",
  },
  elevatedDesc: {
    fontSize: 14,
    color: "#6B7280",
  },
  miniPostBtn: {
    backgroundColor: "#F0F2F5",
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 12,
  },
  miniPostBtnText: {
    fontSize: 12,
    fontWeight: "700",
    color: "#1A2B4A",
  },

  // Staff Cards
  staffSummaryCard: {
    backgroundColor: "#FEF2F2",
    borderRadius: 20,
    padding: 20,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  staffSummaryText: {
    fontSize: 15,
    fontWeight: "600",
    color: "#991B1B",
    flex: 1,
    marginRight: 16,
  },
  quickPostCard: {
    backgroundColor: "#FFFFFF",
    borderRadius: 20,
    padding: 20,
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  quickPostText: {
    fontSize: 15,
    fontWeight: "600",
    color: "#1A2B4A",
  },

  // Feed Section
  feedSection: {
    gap: 16,
  },
  feedTitle: {
    fontSize: 22,
    fontWeight: "800",
    color: "#1A2B4A",
    paddingHorizontal: 20,
    letterSpacing: -0.5,
  },
  categoryScrollContainer: {
    marginBottom: 12,
  },
  categoryScrollContent: {
    paddingHorizontal: 20,
    gap: 8,
  },
  categoryChip: {
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 20,
    backgroundColor: "#FFFFFF",
    shadowColor: "#1A2B4A",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.04,
    shadowRadius: 6,
    elevation: 1,
  },
  categoryChipActive: {
    backgroundColor: "#1A2B4A",
  },
  categoryChipText: {
    fontSize: 14,
    color: "#6B7280",
    fontWeight: "600",
  },
  categoryChipTextActive: {
    color: "#FFFFFF",
  },
  postsList: {
    paddingHorizontal: 20,
    gap: 20,
  },
  postCard: {
    backgroundColor: "#FFFFFF",
    borderRadius: 24,
    padding: 24,
    shadowColor: "#1A2B4A",
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.04,
    shadowRadius: 24,
    elevation: 3,
  },
  alertCard: {
    backgroundColor: "#FEF2F2",
    shadowColor: "#DC2626",
    shadowOpacity: 0.06,
  },
  postHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    marginBottom: 16,
  },
  postAuthorAvatar: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: "#F0F2F5",
    alignItems: "center",
    justifyContent: "center",
  },
  postAuthorInitial: {
    fontSize: 16,
    fontWeight: "700",
    color: "#1A2B4A",
  },
  postAuthorInfo: {
    flex: 1,
  },
  postAuthorName: {
    fontSize: 16,
    fontWeight: "700",
    color: "#1A2B4A",
  },
  postDate: {
    fontSize: 13,
    color: "#6B7280",
    marginTop: 2,
  },
  postTitle: {
    fontSize: 20,
    fontWeight: "800",
    color: "#1A2B4A",
    marginBottom: 8,
    letterSpacing: -0.3,
  },
  postContent: {
    fontSize: 16,
    color: "#4B5563",
    lineHeight: 26,
  },
  viewMoreInline: {
    color: "#A93C40",
    fontWeight: "700",
  },
  eventContainer: {
    marginTop: 20,
    paddingTop: 20,
    borderTopWidth: 1,
    borderTopColor: "#F0F2F5",
    gap: 12,
  },
  eventDetailsRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  eventDetailsText: {
    fontSize: 14,
    color: "#6B7280",
    fontWeight: "500",
  },
  eventFooter: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginTop: 12,
  },
  attendeeCount: {
    fontSize: 14,
    color: "#6B7280",
    fontWeight: "600",
  },
  rsvpActions: {
    flexDirection: "row",
    gap: 8,
  },
  rsvpBtn: {
    paddingHorizontal: 20,
    paddingVertical: 10,
    borderRadius: 16,
    backgroundColor: "#F0F2F5",
  },
  rsvpBtnActive: {
    backgroundColor: "#FEF2F2",
  },
  rsvpBtnText: {
    fontSize: 14,
    fontWeight: "700",
    color: "#1A2B4A",
  },
  rsvpBtnTextActive: {
    color: "#A93C40",
  },
  emptyFeedCard: {
    backgroundColor: "#FFFFFF",
    borderRadius: 24,
    padding: 32,
    alignItems: "center",
    gap: 12,
    marginHorizontal: 20,
    shadowColor: "#1A2B4A",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.03,
    shadowRadius: 12,
    elevation: 2,
  },
  emptyFeedIcon: {
    width: 64,
    height: 64,
    borderRadius: 32,
    backgroundColor: "#F8F9FA",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 4,
  },
  emptyFeedTitle: {
    fontSize: 18,
    fontWeight: "700",
    color: "#1A2B4A",
  },
  emptyFeedDesc: {
    fontSize: 15,
    color: "#6B7280",
    textAlign: "center",
    paddingHorizontal: 20,
    lineHeight: 22,
  },
  coachDashboardContainer: {
    marginBottom: 16,
    gap: 12,
  },
  coachStatsRow: {
    flexDirection: 'row',
    gap: 12,
  },
  coachStatCard: {
    flex: 1,
    backgroundColor: '#FFFFFF',
    borderRadius: 20,
    padding: 16,
    alignItems: 'center',
    shadowColor: "#1A2B4A",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.03,
    shadowRadius: 12,
    elevation: 2,
  },
  statIconBg: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: '#EEF2FF',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 8,
  },
  statValue: {
    fontSize: 24,
    fontWeight: '800',
    color: '#1A2B4A',
    marginBottom: 2,
  },
  statLabel: {
    fontSize: 13,
    color: '#6B7280',
    fontWeight: '500',
  },
  fresherListPreview: {
    backgroundColor: '#FFFFFF',
    borderRadius: 20,
    padding: 16,
    shadowColor: "#1A2B4A",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.03,
    shadowRadius: 12,
    elevation: 2,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  previewTitle: {
    fontSize: 15,
    fontWeight: '700',
    color: '#1A2B4A',
  },
  fresherAvatarsRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  fresherAvatarBubble: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: '#F0F2F5',
    borderWidth: 2,
    borderColor: '#FFFFFF',
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
  },
  fresherAvatarImage: {
    width: '100%',
    height: '100%',
  },
  fresherAvatarText: {
    fontSize: 14,
    fontWeight: '700',
    color: '#1A2B4A',
  },
  fresherAvatarMore: {
    backgroundColor: '#EEF2FF',
  },
  fresherAvatarMoreText: {
    fontSize: 12,
    fontWeight: '700',
    color: '#4338CA',
  },
});
