const express = require('express');
const supertest = require('supertest');
const { pool } = require('../services/db');
const authRoutes = require('../routes/authRoutes');
const errorHandler = require('../middleware/errorHandler');
const authService = require('../services/authService');

const app = express();
app.use(express.json());
app.use('/auth', authRoutes);
app.use(errorHandler);

const request = supertest(app);

describe('Auth Module Integration Tests', () => {
  const testEmail = 'testuser.auth@fresherhub.local';
  const testPassword = 'testpassword123';
  let userId;
  let testRefreshToken;
  let generatedResetToken;

  beforeAll(async () => {
    // Clean up any existing test user first just in case
    await pool.query('DELETE FROM users WHERE email = $1', [testEmail]);

    // Insert a mock user for testing
    const userRes = await pool.query(`
      INSERT INTO users (email, full_name, phone, class_year)
      VALUES ($1, 'Test Auth User', '1234567890', 2026)
      RETURNING id
    `, [testEmail]);
    userId = userRes.rows[0].id;

    // Activate the user for testing login
    await pool.query(`
      INSERT INTO credentials (user_id, password_hash, is_activated, activated_at)
      VALUES ($1, crypt($2, gen_salt('bf')), true, now())
    `, [userId, testPassword]);
    
    // Spy on authService to capture tokens
    jest.spyOn(authService, 'generatePasswordResetToken');
  });

  afterAll(async () => {
    // Clean up
    await pool.query('DELETE FROM users WHERE email = $1', [testEmail]);
    await pool.end();
  });

  describe('POST /auth/login', () => {
    it('should validate missing fields', async () => {
      const res = await request.post('/auth/login').send({ email: testEmail });
      expect(res.status).toBe(400);
      expect(res.body.message).toContain('Validation failed');
    });

    it('should fail with invalid credentials', async () => {
      const res = await request.post('/auth/login').send({ email: testEmail, password: 'wrongpassword' });
      expect(res.status).toBe(401);
      expect(res.body.message).toBe('Invalid credentials');
    });

    it('should succeed with valid credentials', async () => {
      const res = await request.post('/auth/login').send({ email: testEmail, password: testPassword });
      expect(res.status).toBe(200);
      expect(res.body).toHaveProperty('accessToken');
      expect(res.body).toHaveProperty('refreshToken');
      expect(res.body.user.email).toBe(testEmail);
      testRefreshToken = res.body.refreshToken;
    });
  });

  describe('POST /auth/refresh', () => {
    it('should validate missing refresh token', async () => {
      const res = await request.post('/auth/refresh').send({});
      expect(res.status).toBe(400);
      expect(res.body.message).toContain('Validation failed');
    });

    it('should succeed with valid refresh token', async () => {
      const res = await request.post('/auth/refresh').send({ refreshToken: testRefreshToken });
      expect(res.status).toBe(200);
      expect(res.body).toHaveProperty('accessToken');
    });
  });

  describe('POST /auth/logout', () => {
    it('should revoke token successfully', async () => {
      const res = await request.post('/auth/logout').send({ refreshToken: testRefreshToken });
      expect(res.status).toBe(200);
      
      const refreshRes = await request.post('/auth/refresh').send({ refreshToken: testRefreshToken });
      expect(refreshRes.status).toBe(401);
    });
  });

  describe('POST /auth/request-otp', () => {
    it('should successfully mock OTP generation for existing user', async () => {
      const res = await request.post('/auth/request-otp').send({ email: testEmail });
      expect(res.status).toBe(200);
    });
  });

  describe('POST /auth/forgot-password', () => {
    it('should successfully mock password reset token generation', async () => {
      const res = await request.post('/auth/forgot-password').send({ email: testEmail });
      expect(res.status).toBe(200);
      
      // Capture the token generated by the service
      generatedResetToken = authService.generatePasswordResetToken.mock.results[0].value;
      generatedResetToken = await generatedResetToken;
    });
  });

  describe('POST /auth/reset-password', () => {
    it('should fail with invalid token', async () => {
      const res = await request.post('/auth/reset-password').send({
        email: testEmail,
        token: 'invalid-token-here',
        newPassword: 'newsecurepassword123'
      });
      expect(res.status).toBe(400);
    });

    it('should succeed with valid token', async () => {
      const res = await request.post('/auth/reset-password').send({
        email: testEmail,
        token: generatedResetToken,
        newPassword: 'newsecurepassword123'
      });
      expect(res.status).toBe(200);
      expect(res.body.success).toBe(true);

      // Verify login with new password works
      const loginRes = await request.post('/auth/login').send({ email: testEmail, password: 'newsecurepassword123' });
      expect(loginRes.status).toBe(200);
    });
  });
});
